@extends('dashboard/layout')
@section('title')
OrderConstructor - daahboard/steps
@endsection
@section('topmenu')
	@include('dashboard/topmenu')
@endsection
@section('sidebar')
	@include('dashboard/sidebar')
@endsection
@section('footer')
	@include('dashboard/footer')
@endsection
@section('main')
steps
@endsection
@section('guest')
GUEST
@endsection